# coding: utf-8

"""
    Car Rental System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_api_add_car_cars_post(self) -> None:
        """Test case for api_add_car_cars_post

        Api Add Car
        """
        pass

    def test_api_cancel_rental_rentals_rental_id_delete(self) -> None:
        """Test case for api_cancel_rental_rentals_rental_id_delete

        Api Cancel Rental
        """
        pass

    def test_api_get_car_cars_car_id_get(self) -> None:
        """Test case for api_get_car_cars_car_id_get

        Api Get Car
        """
        pass

    def test_api_get_cars_cars_get(self) -> None:
        """Test case for api_get_cars_cars_get

        Api Get Cars
        """
        pass

    def test_api_rent_car_cars_car_id_rent_post(self) -> None:
        """Test case for api_rent_car_cars_car_id_rent_post

        Api Rent Car
        """
        pass


if __name__ == '__main__':
    unittest.main()
